version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.9
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
    ports:
      - "1883:1883"
      - "9001:9001"